@ExampleApp.API_HostAddress = https://localhost:7032

GET {{ExampleApp.API_HostAddress}}/api/Users
Accept: application/json

###

GET {{ExampleApp.API_HostAddress}}/api/Roles

###

POST {{ExampleApp.API_HostAddress}}/api/Roles/Post
Content-Type: application/json

{
  //Role
}

###

PUT {{ExampleApp.API_HostAddress}}/api/Users/Put
Content-Type: application/json

{
  //User
}

###
